---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Должна присутствовать обратная связь с покупателем
  - Все элементы сайта должны быть мультиязычными (русский, английский)
  - При загрузке должна появляться сначала основная информация, затем дополнительная
  - Сайт не должен содержать дефектов
  - Все элементы сайта должны быть читабельными(текст не закрыт картинкой, текст отображается, визуально легко читать информацию)
  - При оформлени заказа данные должны отправляться на сервер
